### PR TITLE
Re-enable OS-X python3.10

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I'm interested in the segfaults issue from #91 and needed an excuse to be added as a maintainer :)  Pardon the noise.

### CODE REVIEW

**Comment by akrherz** [comment]
I didn't get anywhere, but did setup a local reproducer on an old Mac I have.  I did also try the shapely main branch, which will pass all tests except one if I comment out the stray `import pylab` in the examples (no conda-forge matplotlib yet).
```
ERROR: test_polygon_3 (tests.test_singularity.PolygonTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/akrherz/Shapely/tests/test_singularity.py", line 14, in test_polygon_3
    poly = Polygon([p, p, p])
  File "/Users/akrherz/Shapely/shapely/geometry/polygon.py", line 251, in __new__
    geom = pygeos.polygons(shell, holes=holes)
  File "/Users/akrherz/miniconda3/envs/py310/lib/python3.10/site-packages/pygeos/decorators.py", line 80, in wrapped
    return func(*args, **kwargs)
  File "/Users/akrherz/miniconda3/envs/py310/lib/python3.10/site-packages/pygeos/creation.py", line 235, in polygons
    geometries = linearrings(geometries)
  File "/Users/akrherz/miniconda3/envs/py310/lib/python3.10/site-packages/pygeos/decorators.py", line 80, in wrapped
    return func(*args, **kwargs)
  File "/Users/akrherz/miniconda3/envs/py310/lib/python3.10/site-packages/pygeos/creation.py", line 157, in linearrings
    return lib.linearrings(coords, out=out, **kwargs)
ValueError: A linearring requires at least 4 coordinates.
```

can debug this more now locally.

**Comment by jorisvandenbossche** [comment]
> and needed an excuse to be added as a maintainer

Feel free to open a separate PR just for that :)

**Comment by jorisvandenbossche** [comment]
> I did also try the shapely main branch

The main branch is basically a complete rewrite of the low-level code (no longer using ctypes), so for figuring out those segfaults for 1.8, you will need to test with the 1.8 tag or `maint-1.8` branch

Did you succeed to reproduce the segfaults?

**Comment by akrherz** [comment]
> Did you succeed to reproduce the segfaults?

Indeed, but no resolution yet.

**Comment by kmuehlbauer** [comment]
Hi @akrherz @jorisvandenbossche Is there any news on that? Thanks!

XRef: This is currently blocking the migration of `cartopy`(https://github.com/conda-forge/cartopy-feedstock/issues/131).

**Comment by jorisvandenbossche** [comment]
Not yet. The root cause is an issue in the Python / libffi build, and that is being discussed here: https://github.com/conda-forge/python-feedstock/issues/522

**Comment by kmuehlbauer** [comment]
Thanks for the pointer, much appreciated.

**Comment by akrherz** [comment]
@conda-forge-admin restart ci

**Comment by akrherz** [comment]
Exciting times for a Friday evening, awaiting `python-3.10.0-h1248fe1_3_cpython.tar.bz2` and the like to appear in repo metadata!

**Comment by xylar** [comment]
@akrherz, I restarted CI.  Fingers crossed.

**Comment by xylar** [comment]
We're good!  Thank you @akrherz, @jorisvandenbossche, @dopplershift and others for tracking this down!

**Pull request merged**
