### PR TITLE
Add Shapely 1.8rc1 release

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I first merged in the master branch (as a squashed first commit) to update the dev branch with all changes from master. Not sure if that was the best way to update it.

**Comment by jorisvandenbossche** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Looks good.  Is this ready to merge?

**Comment by jorisvandenbossche** [comment]
Yes, I think so

**Pull request merged**
