### PR TITLE
V1.7

### PR DESCRIPTION
**Pull request by ocefpaf**
Just testing. Let's wait for the stable version to update and merge this.

### CODE REVIEW

**Comment by phobson** [comment]
@ocefpaf remind me: will builds of alpha versions like this be available for download/installation? how does that work?

**Comment by ocefpaf** [comment]
> @ocefpaf remind me: will builds of alpha versions like this be available for download/installation? how does that work?

Like I mentioned in https://github.com/conda-forge/shapely-feedstock/pull/49#issue-290845841 this PR is only a test. However, if you want we can create a branch and publish this in a dev channel. It then can be installed with:

```
conda create --name TEST python=3.7 conda-forge/label/dev::shapely
```

**Comment by phobson** [comment]
D'oh I see 🤦‍♂

**Comment by jpmaterial** [comment]
I second (first?) a 1.7a2 version on a dev channel.

**Comment by ocefpaf** [comment]
Let's go with #60

**Pull request closed without merging**
