### PR TITLE
Fix version for 1.8.5.post1

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
This is meant to fix the incorrect build number that we got in #111

**Comment by xylar** [comment]
@ocefpaf, you had removed the `.post` from the version number 4 years ago.  I assume we don't need to be doing that generally, right?

**Comment by xylar** [comment]
based on the discussion in #112 , I"ll just close this

**Comment by ocefpaf** [comment]
Yeah, Sean does things correctly and uses post releases for what they were designed, fixing the release process. B/c in conda we build from source, we don't need them. However, not every developer uses that correctly and we need to watch out! I've seen post releases fixing bugs :-/

**Pull request closed without merging**
